### ISSUE TITLE
Compatibility in macOS Catalina

### ISSUE THREAD

**Issue by wyatt-wong** [paleotronic/microm8-gui#6]
I was unable to run the microm8 GUI in macOS Catalina, is there a compatibility issue ?

**Comment by undefinedopcode** [comment]
Hi Wyatt,

Are you able to provide a screenshot of this issue?  I don't currently have Catalina installed.

April

**Comment by wyatt-wong** [comment]
> Hi Wyatt,
> 
> Are you able to provide a screenshot of this issue? I don't currently have Catalina installed.
> 
> April

I don’t have a screen shot to provide yet but the microM8 GUI app icon just become a STOP icon in macOS Catalina and when I run it, macOS simply said the app is incompatible.

I then tried to download the latest macOS release of FPC but it couldn’t install in macOS Catalina either because it is incompatible. I guess I need to download the FPC source code and see if I can re-compile it under macOS Catalina into binary code first. If the compilation of FPC is successful and can install in macOS Catalina then I will try to do the same for Lazarus source code and finally make use of FPC and Lazarus to compile the microM8 source.

**Comment by retrocomputist** [comment]
[microM8-gui.app.x64.zip](https://github.com/paleotronic/microm8-gui/files/3844370/microM8-gui.app.x64.zip)

**Comment by retrocomputist** [comment]
Thanks Wyatt, I've managed to get a 64-bit version compiled on High Sierra – apparently Lazarus doesn't quite work on Catalina yet

**Comment by wyatt-wong** [comment]
> Thanks Wyatt, I've managed to get a 64-bit version compiled on High Sierra – apparently Lazarus doesn't quite work on Catalina yet

Oh I thought the reason why the microM8 GUI macOS release doesn’t work in Catalina was because Catalina now restrict apps in 64-bit only.
